### ISSUE TITLE
New Update/Patch make RE5 have a Graphic bug

### ISSUE THREAD

**Issue by DarkBringgX** [olegos2/termux-box#11]
New Update/Patch make RE5 have a Graphic/Shadow? Bug when use DXVK 2.2-4-gplasync.
. 
It's working fine before update... Now it's have a Graphic/Shadow? bug. 
. 
![Screenshot_2023-07-18-06-54-28-476_com termux x11](https://github.com/olegos2/termux-box/assets/71298886/17865620-4eca-4658-992b-694dcbb81bf4)

**Comment by Huggo2** [comment]
can you try on 26.06.23 turnip on newest patch?

**Comment by DarkBringgX** [comment]
> can you try on 26.06.23 turnip on newest patch?

I'm already try both Turnip+zink... And it's still have the Graphic/Shadow? bug in the new Update/Patch.
. 
![0 (1)](https://github.com/olegos2/termux-box/assets/71298886/7b7435c4-ba0a-4e0d-97e9-46dbbcece46b)

**Comment by olegos2** [comment]
Should be fixed now. Test it on turnip-main from latest patch.

**Comment by DarkBringgX** [comment]
> Should be fixed now. Test it on turnip-main from the latest patch.

It's Fixed now

**Comment by DarkBringgX** [comment]
> Should be fixed now. Test it on turnip-main from the latest patch.

I'm try to use turnip-main+zink
And It's Fixed now.
.
![0 (2)](https://github.com/olegos2/termux-box/assets/71298886/37f30db8-af10-4bd2-adc4-a0b97e33978e)
