### ISSUE TITLE
Install via chroot: cmd error

### ISSUE THREAD

**Issue by Andy312432** [olegos2/termux-box#12]
OS: Android 13
Soc: s865
Rooted

**Comment by Andy312432** [comment]
![Screenshot_20230720-235159_Termux](https://github.com/olegos2/termux-box/assets/31586206/f04922ef-7f44-4c0c-a2d0-6f9957e3c7a3)

**Comment by Huggo2** [comment]
try installing busybox maybe, but this is the first time i see this error

**Comment by Andy312432** [comment]
> try installing busybox maybe, but this is the first time i see this error

Try changing the script to 
su 0 '...' 
?
Because [in this article ](https://stackoverflow.com/questions/32963479/getting-error-while-using-su-command) , it seems that not every android phone has su -c
