### ISSUE TITLE
Graphics bugs STALKER ShoC

### ISSUE THREAD

**Issue by AnimeAnalPRO** [olegos2/termux-box#13]
The latest update has been installed. There is no problem on DXVK 1.5.5.
![Screenshot_2023-07-21-23-45-42-205_com termux x11](https://github.com/olegos2/termux-box/assets/109460250/87aac6c5-fa0a-47f5-97c0-fdfcbbbc48c2)
Snap 860

**Comment by Huggo2** [comment]
Can you try turnip 26.06.23?

**Comment by AnimeAnalPRO** [comment]
> Can you try turnip 26.06.23?

Yes. Without changes.

**Comment by Huggo2** [comment]
Should be fixed now on turnip-main

**Comment by AnimeAnalPRO** [comment]
This work! Thk!
