### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by drakulaboy** [olegos2/termux-box#14]
Dumb question but how to uninstall
 termux-box?

**Comment by AnimeAnalPRO** [comment]
cleaned and then deleted the application
![IMG_20230724_004731](https://github.com/olegos2/termux-box/assets/109460250/2c737f47-a258-4525-8877-0adc52ffa6a8)
![IMG_20230724_004747](https://github.com/olegos2/termux-box/assets/109460250/f61453b7-003c-4f9b-bbe1-3e7331c0c0d3)

**Comment by Vladik01-11** [comment]
https://github.com/olegos2/termux-box/issues/3#issuecomment-1641951641

**Comment by OmarMammadov** [comment]
rm -rf "file name"

**Comment by Adrwaan** [comment]
If you use root use the command: 
sudo rm -rf ./termux-box && sudo rm -rf $PREFIX/bin/termux-box
If you don't use root, use the command:
rm -rf ./termux-box && rm -rf $PREFIX/bin/termux-box

**Comment by drakulaboy** [comment]
thanks to all
