### ISSUE TITLE
I cant launch it second time

### ISSUE THREAD

**Issue by OmarMammadov** [olegos2/termux-box#19]
As i said i cant launch it second time. It is saying no connection

**Comment by olegos2** [comment]
Try to force stop termux

**Comment by VictorMX2307** [comment]
Same here, stopping both termux and termux-x11 won't work. I'm on a Galaxy S20 FE 5G with Android 13. I've got some logs, but for me they seem normal:
`Dynarec will play moderatly safe with x64 flags
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Cortex-A77 with 8 Cores
Warning, unsupported BOX64_DYNAREC_JVM=0 for [projectzomboid64] in /etc/box64.box64rc
Params database has 24 entries
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 29 Env var
Looking for wine64
argv[1]="explorer"
argv[2]="/desktop=shell,1280x720"
argv[3]="/opt/TFM.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /opt/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec will play moderatly safe with x64 flags
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Cortex-A77 with 8 Cores
Warning, unsupported BOX64_DYNAREC_JVM=0 for [projectzomboid64] in /etc/box64.box64rc
Params database has 24 entries
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for /opt/wine/bin/wine64
argv[1]="explorer"
argv[2]="/desktop=shell,1280x720"
argv[3]="/opt/TFM.exe"
Rename process to "wine64"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /opt/wine/bin/../lib/wine/x86_64-unix/ntdll.so
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec will play moderatly safe with x64 flags
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096 Running on Cortex-A77 with 8 Cores
Warning, unsupported BOX64_DYNAREC_JVM=0 for [projectzomboid64] in /etc/box64.box64rc
Params database has 24 entries
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for /opt/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using emulated /opt/wine/lib/wine/x86_64-unix/libwine.so.1
003c:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x10204b050, syscall 0x50560, not installing seccomp.
003c:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.
003c:fixme:winediag:LdrInitializeThunk wine-staging 8.2 is a testing version containing experimental patches.
003c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
003c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
0044:err:seh:install_bpf Native libs are being loaded in low addresses, sc_seccomp 0x10204b050, syscall 0x50560, not installing seccomp.
0044:err:seh:install_bpf The known reasons are /proc/sys/vm/legacy_va_layout set to 1 or 'ulimit -s' being 'unlimited'.`

**Comment by olegos2** [comment]
I created termux-box on S20FE with sd865 on debloated OneUI 3.1 (Android 11). I never experienced problems with it

**Comment by VictorMX2307** [comment]
Okay I found the problem, I was launching the binary inside the termux-box folder, not the command termux-box. Everything works fine now.
