### ISSUE TITLE
Termux box not working anymore

### ISSUE THREAD

**Issue by KintCark** [olegos2/termux-box#25]
Man I really  like termux-box  but now when I installed it it not show in termux x11 it doesn't even have custom wine option anymore. 😕

**Comment by KintCark** [comment]
Can u please add open gl and proton 8.0-3 please

**Comment by olegos2** [comment]
Custom wine option is still in preferences, instructions will be shown when this option is selected. Install 8.0-3 manually. Try reinstalling termux, termux-x11 completely, download them from termux-box readme. OpenGL works by default if I understood your question correctly.

**Comment by KintCark** [comment]
Hey can u tell me how to install custom wine where do I get proton 8.0-3
please make video?

**Comment by olegos2** [comment]
Continued in #29, so closing this issue
