### ISSUE TITLE
Termux-box not connecting to Termux-x11

### ISSUE THREAD

**Issue by GabiAle97** [olegos2/termux-box#31]
Fresh install of proot version of Termux-box with latest patches.
Shows "Starting. Open termux-11 app..." but when termux-11 is open, nothing shows up.
Tried cleaning data of Termux and reinstalling but no luck

**Comment by Huggo2** [comment]
Try redownload termux-x11 now, and in termux copy and run this, or reinstall:

cd $HOME/termux-box
wget https://github.com/olegos2/termux-box/raw/main/components/termux-x11-1.02.07-0-all.deb &>/dev/null
dpkg -i termux-x11-1.02.07-0-all.deb &>/dev/null
rm -rf termux-x11-1.02.07-0-all.deb
cd

**Comment by GabiAle97** [comment]
Completely solved. Thanks!
