### ISSUE TITLE
Can't use DXVK? (Crash) after new Updates/Patch? 

### ISSUE THREAD

**Issue by DarkBringgX** [olegos2/termux-box#4]
New Patch/Update Termux-box make some games crash when use DXVK ( maybe not all game but it's crash for some game that I try  ) 
. 
But... the Game is Working fine Before new Patch/Update
And I still can use DXVK... and it's always crash rn after the new Patch/Update.
.
i hope this problem can be Fixed.

**Comment by Huggo2** [comment]
is this fixed after last patch?

**Comment by DarkBringgX** [comment]
> 



> is this fixed after last patch?

Yeah... It's working fine now
. 
I can use DXVK again and no crash to the game that previously crash.

**Comment by Huggo2** [comment]
:)
