### ISSUE TITLE
How to fix winetricks

### ISSUE THREAD

**Issue by AnimeAnalPRO** [olegos2/termux-box#43]
How to return the graphical shell instead of the command line in Termux.
Reset prefix and wine does not help.
![Screenshot_2023-08-13-20-56-04-158_com termux](https://github.com/olegos2/termux-box/assets/109460250/cb3a8835-548f-4ca3-9920-aa90fbdef23e)

**Comment by olegos2** [comment]
I don't get this message when starting from termux-box menu. Can you reinstall and check if it's fixed?

**Comment by AnimeAnalPRO** [comment]
the latest update does not fix this.

**Comment by BiatuAutMiahn** [comment]
I just installed last night and I didnt have any issues with winetricks, what are you trying to install? Oh and I noticed that I had to keep switching between X11 and terminal to get it going again. Like termux is sleeping when its not active, even set battery mode to unoptimized. Start winetricks, goto X11, wait...nothing. Go back to terminal wait...progress, then back to X11 winetricks is there. It's similar with installing dll/components, I often had to go back and forth to keep dialogs appearing and dismissing/accepting dialogs.

**Comment by AnimeAnalPRO** [comment]
I tried your advice didn't help. Termux X11 closes immediately after clicking OK where you need to select the default winetricks.

**Comment by BiatuAutMiahn** [comment]
Ah, I can't say then cause It worked both on my Quest 2 and my Samsung S21

**Comment by skyne98** [comment]
Still happening, any known fixes?

**Comment by skyne98** [comment]
Says `ZINK` is an unknown argument.

**Comment by BiatuAutMiahn** [comment]
without seeing log/console output it's hard to say.

**Comment by AnimeAnalPRO** [comment]
Maybe it's because of Termux:X11 because of dev build. Somehow I don't need it anymore.
