### ISSUE TITLE
Pulseaudio leftovers

### ISSUE THREAD

**Issue by DocMAX** [olegos2/termux-box#45]
After existing i have a dozen of pulseaudio processes left. Can you fix this please?

**Comment by nerdydumbykier** [comment]
Yeah, this has been bugging me quite a bit but I have a "temporary" solution which is to add
`pkill pulseaudio` after the line that says `pkill -f "app_process / com.termux.x11"` in the termux-box script which is in `/data/data/com.termux/files/usr/bin/termux-box`.
Works everytime for me.

**Comment by olegos2** [comment]
Should be fixed with latest patch
