### ISSUE TITLE
TFM is not working 

### ISSUE THREAD

**Issue by AlanbrTKJ** [olegos2/termux-box#53]
TFM is not working since I did the last update, I already uninstalled and reinstalled and the error continues, it worked a few times and then tfm does not open anymore

**Comment by olegos2** [comment]
That's a third party virus either from exagear cache or from other .exe files you ran. You can scan your TFM.exe and you will see floxif virus. It's not related to termux-box

**Comment by AlanbrTKJ** [comment]
Thank you, I didn't know that, I managed to solve the problem
