### ISSUE TITLE
Termux-box installation script erased all my storage

### ISSUE THREAD

**Issue by admo64** [olegos2/termux-box#56]
Only the Android folder was left, all my apps are still running with they own saved data. Fortunately I made a backup of my photos not so long ago, so I kinda appreciate the extra space but such bug is very dangerous.

The storage erasing happened in some point between this steps. I did NOT run any command in termux, only the installation script of termux-box

1. Install termux-box in chroot 
2. Since steam wasn't working I tried to change to Proot containing method. After doing in the settings of termux-box it said something like "./start-proot.sh" not found
3. Tried to rerun the installation script, this time it showed many "can't erase xxxxxx" in a "ubuntu-sh" folder
4. Selected Proot for installation and again it said "./start-proot.sh" not found
5. Cleaned all the data of termux in android settings
6. Reinstalled termux-box, this time there wasn't any error messages
7. Selected Proot and again didn't work
8. Erased termux data in android settings
9. Denied root permissions to termux
10. Reinstall termux-box, many "denied permission" showed up
11. Selected Proot again and after a few "denied permission" it just stops and does nothing

After this is when I realized that all my storage was gone

**Comment by romanovj** [comment]
you didn't unmount folders before

**Comment by PerroLoco64** [comment]
I see, never saw uninstall instructions so I thought it was enough cleaning the data. May I ask how to properly uninstall so this doesn't happen again?

**Comment by romanovj** [comment]
the safest way is to delete whatever you want after reboot

**Comment by PerroLoco64** [comment]
Well, I actually the day before was trying various options, box64droid, winlator until termux-box which was the one I liked the most. Today in the morning while trying to boot box64 in proot was when my storage was erased, so I don't know if was the install script fault or a termux app bug.

I redid the steps I wrote but it did not erase anything. I guest I have to reboot every time I have to reinstall and hope it doesn't happen again.

May I ask that if I manually execute the script start-proot.sh inside the termux-box folder does boot box64 properly in proot containment?

**Comment by olegos2** [comment]
Unmount problems can sometimes happen. I don't have root and I can't fix all chroot problems yet

**Comment by bharteja** [comment]
Guys don't you erase them manually in file manager

**Comment by MohamadOday** [comment]
Hey, How can I avoid this? What is the proper way of uninstallation?

**Comment by admo64** [comment]
The safest way is to uninstall after a reboot. After rebooting you can either use the script option to uninstall if available or erase termux app data
