### ISSUE TITLE
Gui freeze after loading

### ISSUE THREAD

**Issue by ander1245** [olegos2/termux-box#67]
![Screenshot_2023-09-28-20-34-01-308_com.termux.x11.jpg](https://github.com/olegos2/termux-box/assets/65908980/72f38c27-f7b0-495b-98ef-5c675749f2fa)

I cant do anything

**Comment by ander1245** [comment]
I don't know why but without logs it freeze

**Comment by ander1245** [comment]
No after 1-25 seconds gui freeze

**Comment by olegos2** [comment]
This was updated box builds issue with Wine 8.2 staging. I changed scripts so that when you select Wine 8.2, previous builds are automatically installed

**Comment by meepo161** [comment]
> This was updated box builds issue with Wine 8.2 staging. I changed scripts so that when you select Wine 8.2, previous builds are automatically installed

Oppo find x6 pro, 8.14 same. Freeze after loading(1-25 sec). Antifreeze after rotate device or wrap unwrap termux11

**Comment by meepo161** [comment]
Why closed?

**Comment by arif932264** [comment]
> This was updated box builds issue with Wine 8.2 staging. I changed scripts so that when you select Wine 8.2, previous builds are automatically installed

Please help me, how do I do it ?
