### ISSUE TITLE
Советую поменять версию proton на 8.13

### ISSUE THREAD

**Issue by BloodANGELdb** [olegos2/termux-box#70]
Советую поменять версию proton на 8.13, так как на 8.2 не корректно запускаются некоторые exe ,  редко какие установщики работают без ошибок, в proton 8,14 и выше не работает GPU_Caps_Viewer,  игры некоторые не запускаются или вылетают так как ускоритель работает не корректно, на proton 8.13 все работает корректно, все устанавливается и запускается.

**Comment by fenndooscar** [comment]
Откуда можно скачать proton 8.13 для termux-box?
