### ISSUE TITLE
Skyrim LE stuck after several minutes in the game

### ISSUE THREAD

**Issue by DarkBringgX** [olegos2/termux-box#8]
Skyrim LE
The game is working fine when I try to open it on Termux-box
. 
But it's stuck after several minutes in game
And the sound is still running in the background.. But the game is stuck.

**Comment by jotesoft** [comment]
I am having smiler problem. I used same driver and same setting on Exagear and winlator and both are running the game but Termux-box getting stuck after loading screen and sound playing in the background.
