### ISSUE TITLE
virgl_test_server + libGL.so.1?

### ISSUE THREAD

**Issue by DocMAX** [olegos2/termux-box#92]
Who is maintaining those special builds? Where can i find the latest version? They are much faster than the original Termux.

**Comment by olegos2** [comment]
Virgl server from alexvorxx repo. libGL.so.1 is mesa virgl with some patches, built for termux-box by Hugo. https://github.com/alexvorxx/Mesa-VirGL/releases/tag/v0.0.1

**Comment by DocMAX** [comment]
Answered, so this issue is fixed
